import os
from dotenv import load_dotenv
from typing import Annotated
from typing_extensions import TypedDict
from langgraph.graph import StateGraph, START, END
from langgraph.graph.message import add_messages
from langchain_openai import ChatOpenAI
from langchain_core.messages import SystemMessage

load_dotenv()

# ---------------------------------------------------------
# 1. Define the "State"
# ---------------------------------------------------------
# In LangGraph, the State is the memory object passed from node to node.
# Here, our state is simply a list of messages. The `add_messages` reducer
# tells LangGraph to append new messages to the existing list, rather than overwrite it.
class State(TypedDict):
    messages: Annotated[list, add_messages]

# ---------------------------------------------------------
# 2. Define the Nodes (The functions that do the work)
# ---------------------------------------------------------
# We initialize the LangChain wrapper for OpenAI
llm = ChatOpenAI(model="gpt-4o-mini")

def chat_model_node(state: State):
    """This node takes the current state (message history) and asks the LLM for a response."""
    # We can inject a system message if it's the very first turn
    messages_to_send = state["messages"]
    if len(messages_to_send) == 1:
        # User just sent their first message, let's prepend a system prompt
        messages_to_send = [SystemMessage(content="You are a helpful, very brief LangGraph assistant.")] + messages_to_send
        
    response = llm.invoke(messages_to_send)
    
    # We return a dictionary that updates our State. 
    # Because we used `add_messages`, this gets appended to the history!
    return {"messages": [response]}


# ---------------------------------------------------------
# 3. Build the Graph
# ---------------------------------------------------------
# Initialize a graph that expects our State schema
graph_builder = StateGraph(State)

# Add our single node to the graph and name it "chatbot"
graph_builder.add_node("chatbot", chat_model_node)

# Define the flow: Start -> Chatbot -> End
graph_builder.add_edge(START, "chatbot")
graph_builder.add_edge("chatbot", END)

# Compile the graph into an executable application
app = graph_builder.compile()

# ---------------------------------------------------------
# 4. Run the Agent Loop
# ---------------------------------------------------------
def main():
    print("🕸️ Welcome to Module 4: LangGraph Coordinator!")
    print("This is your first compiled StateGraph running a loop.\n")
    print("Type 'exit' to quit.\n")

    # In LangGraph, we typically pass the state through via a configuration thread
    # so we can maintain persistent memory. For this simple demo, we will manually
    # loop and pass the updated state back in. 
    # (Note: proper persistent memory tracking via 'checkpointers' will be covered in Module 5!)
    
    # We start with empty history for this session
    session_messages = []

    while True:
        user_input = input("You: ")
        if user_input.lower() in ['exit', 'quit']:
            break

        # Append user message to our local session var
        session_messages.append(("user", user_input))

        # We "stream" the execution of the graph.
        # This yields updates from every node as it happens.
        for event in app.stream({"messages": session_messages}):
            # The event is a dictionary keyed by the node name (e.g., "chatbot")
            for node_name, state_update in event.items():
                print(f"   [Node executed: {node_name}]")
                # Grab the latest message generated by that node
                latest_msg = state_update["messages"][-1]
                print(f"\nAssistant: {latest_msg.content}\n")
                
                # Update our local session history so the next loop remembers!
                session_messages.append(("assistant", latest_msg.content))

if __name__ == "__main__":
    main()
